spring:
 datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://60.205.224.98:3306/blog?useUnicode=true&characterEncoding=utf-8
     username: root
     password: 123456
 jpa:
   hibernate:
     ddl-auto: none
   show-sql: false

 # REDIS (RedisProperties)
 redis:
   host: 60.205.224.98
   port: 6379
   # Redis数据库索引（默认为0）
   database: 0
   pool:
     # 连接池最大阻塞等待时间（使用负值表示没有限制）
     max-wait: -1
     # 连接池中的最大空闲连接
     max-idle: 8
     # 连接池最大连接数（使用负值表示没有限制）
     max-active: 8
     # 连接池中的最小空闲连接
     min-idle: 0
   # 连接超时时间（毫秒）
   timeout: 0
   version: pro






logging:
  level:
    root: info
    com.zxh: info
  file: log/blog-pro.log

server:
  port: 80

redis:
  area: blog
  tags:
    top:
      key: tagsTop
  types:
    top:
      key: typesTop
  blogs:
    top:
      key: blogsTop
  recommendblogs:
    top:
      key: recommendblogsTop


